-- SQL Schema for RushNG Supabase Database
-- Run this in your Supabase SQL Editor

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    role TEXT CHECK (role IN ('buyer', 'seller', 'rider', 'admin')),
    status TEXT DEFAULT 'offline',
    is_verified BOOLEAN DEFAULT false,
    has_opay BOOLEAN DEFAULT false,
    opay_data JSONB,
    shop_address JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Feedback Table
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    seller_id UUID REFERENCES public.users(id),
    rider_id UUID REFERENCES public.users(id),
    product_name TEXT NOT NULL,
    pickup JSONB NOT NULL,
    dropoff JSONB NOT NULL,
    status TEXT DEFAULT 'pending',
    fare NUMERIC NOT NULL,
    distance NUMERIC,
    rider_location JSONB,
    rider_confirmed BOOLEAN DEFAULT false,
    buyer_confirmed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Activity Logs Table
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- 6. Policies for Users Table
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON public.users FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- 6. Policies for Feedback Table
CREATE POLICY "Anyone can insert feedback" ON public.feedback FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view feedback" ON public.feedback FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can delete feedback" ON public.feedback FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- 7. Policies for Orders Table
CREATE POLICY "Sellers can view their orders" ON public.orders FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "Riders can view their orders" ON public.orders FOR SELECT USING (auth.uid() = rider_id);
CREATE POLICY "Riders can view pending orders" ON public.orders FOR SELECT USING (status = 'pending');
CREATE POLICY "Sellers can create orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "Riders can update their assigned orders" ON public.orders FOR UPDATE USING (auth.uid() = rider_id OR auth.uid() = seller_id);
CREATE POLICY "Admins can view all orders" ON public.orders FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- 8. Policies for Activity Logs Table
CREATE POLICY "Admins can view all activity logs" ON public.activity_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Anyone can insert activity logs" ON public.activity_logs FOR INSERT WITH CHECK (true);

-- 9. Enable Real-time for all tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
ALTER PUBLICATION supabase_realtime ADD TABLE public.feedback;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.activity_logs;
